Frontend refactors
mlte-team/mlte pull request #367
Opened 2024-03-07 19:25 UTC by sei-aderr

Addresses all points in #359

2024-03-07 20:18 UTC, sebastian-echeverria requested changes
Changes look ok, but take a look at my comment below to see if we could add that as an internal improvement as well. Having that hardcoded server URL is a pain, but having it duplicated all over the code is worse. Might be a good time to reduce that duplication.

2024-03-07 20:18 UTC, sebastian-echeverria commented on mlte/frontend/nuxt-app/pages/index.vue
> +  await $fetch("http://localhost:8080/api/model/" + modelName + "/version", {
Could you reduce the duplication of the hardcoded localhost:8080 path in some way? Such as by having a base fetch function that fetchArtifact and these other fetches call?

2024-03-12 20:06 UTC, sebastian-echeverria approved these changes
Nice! This actually addresses #252. Sending this to Kate for her review.

2024-03-12 20:10 UTC, sei-aderr commented
I think it is close to addressing that, but not 100% of the way there. Kyle's idea with that was to be able to feed in the backend URL with a CLI command or something so that it was configurable from a user perspective which one to point it at. I could set up a prod/dev endpoint or something similar but I am not sure how I would go about providing a way for the user to edit that value during the use of the package.

2024-03-12 20:49 UTC, sebastian-echeverria commented
Ok, fair enough. We can deal with that improvement later.

2024-03-12 21:45 UTC, krmaffey approved these changes
This looks great, thanks both!

2024-03-12 22:00 UTC, merged